### ISSUE TITLE
✨ feat: ArchiveView

### ISSUE THREAD

**Issue by JYPjoy** [DeveloperAcademy-POSTECH/MC3-Team13#11]
### 📝 작업 목적 / Miro / Figma

보관함 뷰에 대한 설계

### 🛠️ Tasks
* [x] UI 요소 그리기
* [x] 모델 선언 
* [x] Realm 사용
* [x] Realm 사용해서 DB 설계하기
* [x] 버튼 이벤트 로직 처리
