### ISSUE TITLE
🐛 fix: 실시간 녹음 분석 기능 오류

### ISSUE THREAD

**Issue by mininim** [DeveloperAcademy-POSTECH/MC3-Team13#31]
### 📝 작업 목적 / Miro / Figma

실시간 녹음 분석할때 오류 고치기

---

### 🛠️ Tasks

* [x] 실시간 녹음 후 분석하면 발생하는 오류 해결하기

**Comment by mininim** [comment]
- [ ] 전체 스크립트 출력함수 - 분석용
- [ ] 마지막 detailWpm 구하는 기능 오류 수정
- [ ] 전체 전체 wpm 확인

**Comment by mininim** [comment]
AnalysisViewModel transcribe 메소드 일부분
print(res) 값들과 최종 transcripts 출력값이 다르게 나타남
```swift
let task = speechRecognizer.recognitionTask(
                    with: request,
                    resultHandler: { (result, error) in
                        // MARK: 음성을 차례대로 정확하게 변환하기 위해
                        if result == nil {
                            self.transcripts.append("(대화 없음)")
                            completion(true)
                        } else if (result?.isFinal)! {
                            if let res = result?.bestTranscription.formattedString {
                                // 결과 Transcripts 추가
                                self.transcripts.append(res)
                                // detail Wpms 추가
                                self.addDetailWpms(textPerMinute: res)
                                print(">>>###***>>>\(res)")
                                completion(true)
                            }
                        }
                    })
```
